### ISSUE TITLE
Missiles jump back

### ISSUE THREAD

**Issue by Ulydev** [OpherV/spaaace#6]
Hello! First of all, thanks for your work on Incheon, it looks like a great project so far.
I'm running into an issue (but is it really one?) while playing Spaaace.

The missiles seem to jump back to be on par with the server:
https://media.giphy.com/media/26xBzrKIJfH0mt29i/giphy.gif

Is this what is supposed to happen? Is it linked to latency? Why does this happen?
Thanks in advance for your answers, I'm kind of new to networking so every tiny piece of explanation helps :)

**Comment by namel** [comment]
Hi @Ulydev that's some impressive shooting you got there.

It's hard to tell from the gif so I will take a closer look on the server tomorrow.  I think what you're seeing
is the missile flying fast and then suddenly slowing down too much.  Is that a good description of what you are seeing?

What latency are you running at (it should say at the top left corner).  I'm also curious if you are seeing
this effect when you run locally.

Here is a description of what happens. When you fire a missile, there is a temporary client-version of the missile (we call it a shadow object) which eventually gets replaced by the server-version of the missile once that becomes available. My guess at this point is that the bending adjustment used when the shadow object is replaced by the server object is too aggressive.  I'll take a closer look tomorrow.

**Comment by Ulydev** [comment]
Hi @namel , thanks for your reply! 
What I'm experiencing is the missiles being teleported back to where they were a few milliseconds earlier.

![gif](https://media.giphy.com/media/l3q2ZC1RaLit0ub1C/giphy.gif)

Maybe it's just latency and I shouldn't worry about it, though.
I appreciate the explanations and I'm looking forward to seeing more amazing progress on Incheon! :)
